# Textes de choix de l'Acte 3.

ACT_3_CHOICES = {'scene_21_route_du_nord': {'options': ["Suivez la vision de l'Œil sans détour, quitte à épuiser le Fragment avant même d'atteindre Ashkar",
                                        "Votre allié politique peut ouvrir des routes plus sûres, et les tunnels de Borin restent la meilleure garantie pour les emprunter sans y laisser votre groupe"]},
 'scene_21a_col_des_morsures': {'options': ['Secourir les éclaireurs, quitte à retarder votre propre course vers Garrick',
                                            'Comprendre qui tient vraiment le col avant de vous y engager : examinez les fanions cendreux',
                                            'Forcer la marche, avant que la tempête ne referme pour de bon la route de Fort-Nord',
                                            'Négocier un passage discret avec les convoyeurs de Cendres, quitte à leur devoir un service que vous ignorez encore']},
 'scene_21b_camp_des_lanternes_froides': {'options': ['Demandez à Lyra ce qu’elle craint vraiment dans les Cristaux, au risque d’une réponse que vous ne vouliez pas entendre',
                                                      'Penser à Garrick, encore et encore, en préparant ce que vous lui direz une fois libre',
                                                      'La lanterne verte garde peut-être un murmure de la montagne — écoutez-la, même si le sommeil doit y passer']},
 'scene_22_forteresse_de_givre': {'options': ['Libérez Garrick tout de suite, sans même savoir ce que voulaient ses geôliers',
                                              'Pourquoi a-t-il menti toute votre vie ? Exigez une réponse avant de briser ses chaînes',
                                              "Le Cristal de Vie bat derrière lui — l'examiner d'abord, quitte à le faire attendre"]},
 'scene_22a_approche_de_la_forteresse': {'options': ['Entrer en force par la porte principale, pour attirer les gardes loin des prisonniers',
                                                     'Faire confiance au flair de Borin pour trouver un passage nain oublié, en laissant l’Œil d’Aeternis repérer les patrouilles restantes au prix d’une vision douloureuse']},
 'scene_22b_verite_de_garrick': {'options': ['Pourquoi n’a-t-il jamais parlé du rôle des Porteurs, même quand vous suppliiez de comprendre votre propre marque ?',
                                             'Le serrer contre vous d’abord, les explications viendront ensuite — vous en avez tous deux besoin',
                                             'Les mensonges attendront : le Cristal de Vie et Fort-Nord passent avant tout']},
 'scene_23a_prix_du_cristal_de_vie': {'options': ['Prendre le Cristal tout entier pour sauver Elderia, quitte à ce qu’un lieu précis en paie le prix',
                                                  'Épargner Ashkar : laissez-lui une part de l’énergie plutôt que de condamner la montagne qui vous a accueillis',
                                                  'Demandez à Garrick comment porter, sans se perdre, un pouvoir qui soigne autant qu’il affame',
                                                  'Convoquer les anciens d’Ashkar pour décider ensemble du prix à payer, plutôt que de trancher seul face au Cristal']},
 'scene_23b_conseil_ashkar': {'options': ['Préparer une route militaire avec les ressources de votre alliance, quitte à en payer le prix politique plus tard',
                                          'Rester discret : une route silencieuse tiendrait Malakar loin de vos mouvements',
                                          'Comparez d’abord les visions du Fragment, les archives d’Aldorath et les cartes de Garrick avant de trancher']},
 'scene_23c_cicatrice_ashkar': {'options': ['Rester auprès des mineurs blessés, organiser les secours plutôt que repartir aussitôt',
                                                                                        'Sécuriser Fort-Nord avant le retour des Cendres, puis étudier les racines ternies pour savoir ce qu’un Cristal coûte vraiment à sa terre']},
 'scene_23d_heritage_de_garrick': {'options': ['Pardonnez-lui, sans effacer pour autant ce qu’il a caché pendant toutes ces années',
                                                                                             'Exigez qu’il dise enfin tout ce qu’il sait sur Malakar et Morvayn, sans plus rien épargner',
                                                                                             'Comment survivre à la marque sans devenir, un jour, un autre Morvayn ?']},
 'scene_23e_serment_des_compagnons': {'options': ['Promettre de préserver les peuples touchés par les Cristaux, même si cela ralentit chaque victoire à venir',
                                                  'Demandez à vos compagnons de vous contredire au besoin, même au pire moment d’une bataille',
                                                  'Refuser tout serment et garder seul le poids du choix, quitte à isoler un peu plus votre marque',
                                                  'Rendre le Cristal de Vie à Ashkar, renoncer à la Chasse — malgré tout ce que cela laisse à Malakar']},
 'scene_24_routes_des_cristaux': {'options': ['Le Cristal des Ombres attend dans une cité morte, quitte à réveiller ce qui y dort encore',
                                              'Et le Cristal des Esprits, dans le monde spectral ? Au risque d’y perdre plus qu’un peu de sommeil',
                                              'Les îles englouties gardent le Cristal des Marées, là où les cartes elles-mêmes hésitent à s’aventurer']},
 'scene_24b_resonance_cristal_choisi': {'options': ['Laissez Lyra vous ancrer dans le présent plutôt que de vous y perdre entièrement',
                                                                                                        'Demandez à Garrick d’interpréter l’appel du Cristal, mot après mot',
                                                                                                        'Suivre la résonance avec le Fragment malgré la douleur : c’est le prix pour en apprendre davantage']},
 'scene_24d_route_du_cristal_choisi': {'options': ['Avancez lentement — mieux vaut comprendre le Cristal avant qu’il ne vous comprenne mieux que vous',
                                                   'Cacher les manifestations aux troupes pour éviter la panique, quitte à perdre leur confiance plus tard',
                                                   'Les signes du Cristal peuvent faire gagner du temps sur la route, quel qu’en soit le prix sur votre corps']},
 'scene_24a_epreuve_second_cristal': {'options': ['Protégez d’abord les survivants liés au Cristal, même si cela retarde votre victoire',
                                                  'Forcer l’épreuve avec le Fragment du Temps pour gagner des jours, au prix d’une douleur à cacher',
                                                                                                    'Laissez Garrick et Lyra choisir ensemble la solution la moins destructrice plutôt que de trancher seul']},
 'scene_24e_perte_avant_la_guerre': {'options': ['Secourir ceux qui peuvent encore revenir à eux, quitte à laisser filer la trace encore chaude de Malakar',
                                                 'Poursuivez la trace de Malakar avant que la neige ne l’efface pour de bon',
                                                 'La marque sur le mur pourrait répondre à la vôtre — l’étudier malgré tout ?',
                                                 'Envoyer Lyra en éclaireuse discrète sur la trace de Malakar, sans engager le reste du groupe']},
 'scene_24c_presage_de_guerre': {'options': ['Prévenir officiellement votre allié politique, au risque de transformer votre route en affaire d’État',
                                                                                         'Des messagers discrets, avant les proclamations officielles, pour garder encore un peu de marge de manœuvre',
                                                                                         'Appeler toutes les factions à une coalition de guerre, même celles qui vous doivent le moins']}}
