# Textes de choix de l'Acte 2.

ACT_2_CHOICES = {'scene_13a_quartiers_aldorath': {'options': ["Foncer dans la faille et suivre les échos avant qu'ils ne s'effacent, quoi qu'en dise le Fragment",
                                                              'Étudier le phénomène avec méthode, même si la place semble retenir son souffle et que chaque seconde vous échappe un peu',
                                                              'Prévenir la Cour et laisser les preuves passer entre des mains politiques peu pressées']},
 'scene_13d_fille_aux_corbeaux': {'options': ["Faire confiance à Mira aux Corbeaux, quitte à lui devoir une faveur dont elle fixera seule le prix",
                                              "L'interroger sans détour, avant qu'elle ne transforme votre urgence en marchandage",
                                              'La livrer aux gardes ? Une sécurité immédiate, payée au prix de la Basse-Ville et de tout ce qu’elle aurait pu vous apprendre']},
 'scene_13e_taverne_dragon_gris': {'options': ['Recruter deux mercenaires du Dragon Gris pour couvrir votre entrée dans la Prison des Cendres',
                                               'Écouter les rumeurs sur Garrick, même celles qui sentent la bière et le mensonge, en espérant qu’une seule dise vrai',
                                               'Aider ces réfugiés, quitte à ralentir votre propre quête',
                                               'Défier un habitué costaud à un bras de fer pour gagner le respect de la taverne, quitte à y laisser votre orgueil']},
 'scene_14_conseil_royal': {'options': ["Soutenir l'armée du duc Verdan : des soldats, des portes ouvertes, et des dettes militaires qui pèseront tôt ou tard",
                                        "Soutenir l'Église du grand prêtre Solan, où les secrets se déguisent en prières et où la foi couvre parfois le pouvoir",
                                        "Parier sur Corvus et sa plume plutôt que sur l'épée de Verdan"],
                            'demandes': ['Exiger une piste officielle sur Garrick devant toute la Cour assemblée',
                                         'Demander une protection contre Morvayn, même si une escorte ressemble parfois à une laisse tenue par une main royale',
                                         'Refuser toute tutelle de la Cour et garder votre liberté']},
 'scene_14b_fragments_du_mensonge': {'options': ['Dire la vérité et exposer Morvayn, quitte à diviser brutalement la cour',
                                                 "Laisser Lyra témoigner à votre place, au risque de l'exposer aux soupçons d'Aldor et de lui faire porter le poids de votre silence",
                                                 'Menacer Varos de révéler ses propres liens avec Varken']},
 'scene_14c_archives_aldor': {'options': ['Creuser encore les documents, au risque de se perdre dans des dates qui ne devraient pas coexister',
                                          "Montrer le document à Lyra : partager le poids d'une vérité encore incomplète plutôt que la porter seul",
                                          'Garder le secret. Dans ces couloirs, même les scribes semblent avoir une allégeance, et vous ignorez encore qui trahit qui']},
 'scene_17_ambassade_elfique': {'options': ['Entrer immédiatement et forcer Ellorien à répondre en face',
                                            'Espionner la réunion depuis les jardins, là où les feuilles cachent mieux que les murs et où la vérité se glane sans confrontation',
                                            "Attendre Lyra et respecter un silence qu'elle n'a pas encore choisi de rompre, même si l'attente vous ronge"]},
 'scene_13b_disparus_aldorath': {'options': ["Accepter l'Œil pour lire les traces du Temps, même si la relique réclame sa part de douleur",
                                             "Le laisser au temple et ne demander que l'aide des prêtres",
                                             "Le prendre en secret, avant que la couronne ne l'enferme dans un coffre où il ne servira plus jamais personne"]},
 'scene_17b_nuit_des_masques': {'options': ['Approcher le duc Verdan, dont la loyauté marche toujours au pas des soldats',
                                            'Approcher Corvus, qui sourit rarement sans cacher trois calculs derrière ses lunettes',
                                            "Approcher Solan et écouter ce que la foi d'Aldor murmure quand personne ne prêche, entre deux coupes de vin sacré"]},
 'scene_17c_visage_de_morvayn': {'options': ['Provoquer Morvayn, au risque de précipiter un combat que vous ne maîtrisez pas encore',
                                             "L'écouter jusqu'au bout, même si chaque phrase rend Malakar moins simple à haïr",
                                             "Tenter de l'arrêter avant que le bal ne comprenne qu'un monstre danse parmi lui, quitte à transformer la fête en chaos"]},
 'scene_17d_philosophie_du_feu': {'options': ["L'accuser d'utiliser la peur pour justifier les massacres",
                                              'Lui demander pourquoi Malakar a peur, puisque cette question semble brûler sous toutes les autres',
                                              "Tenter de l'arrêter au milieu du bal, quitte à transformer les masques en panique"]},
 'scene_15b_lettre_cachee': {'options': ['Montrer les lettres à Lyra plutôt que de porter seul la blessure de Garrick',
                                         'Détruire les lettres, pour que ces aveux ne deviennent jamais des armes politiques',
                                         "Les garder en secret : certaines vérités doivent attendre le bon témoin avant d'être dites à voix haute"]},
 'scene_16_prison_des_cendres': {'options': ["Lancer l'assaut frontal et prouver aux Cendres que vous n'êtes plus une proie",
                                             'Chercher une infiltration par la falaise noire, loin des torches et des cris, quitte à perdre un temps précieux',
                                             'Négocier ? Une prison garde parfois plus de peur que de loyauté'],
                                 'objectifs': ['Chercher Garrick avant tout, quitte à faire payer aux autres captifs le prix de votre priorité',
                                               'Sécuriser les prisonniers : votre quête ne doit pas avaler les autres vies enfermées ici',
                                               "Récupérer les preuves sur les Porteurs pour comprendre la guerre avant d'y survivre"]},
 'scene_16a_cellules_abandonnees': {'options': ['Libérer Elara et parier que son savoir vaut le risque',
                                                "L'interroger longuement avant de la laisser derrière vous sans lui offrir votre confiance ni votre aide"]},
 'scene_16d_prisonnier_sans_age': {'options': ['Lui faire confiance, même si sa voix semble parler depuis plusieurs époques à la fois',
                                               "Refuser de croire ses énigmes tout en le libérant par prudence, sans jamais lui offrir votre confiance"]},
 'scene_16c_registres_interdits': {'options': ["Montrer les documents à Lyra et confronter Ellorien à ce qu'elle a préféré oublier",
                                               "Transmettre une copie discrète à la Reine tout en gardant l'original caché, refusant de tout dévoiler d'un coup"]},
 'scene_16b_borin_prisonnier': {'options': ["Libérer Borin et l'accepter dans le groupe, avant que la prison ne choisisse à votre place",
                                            "Lui demander d'abord ce qu'il sait sur Garrick et sur les serments nains qu'on lui a arrachés",
                                            "Le laisser aux autorités d'Aldor, pour éviter un incident diplomatique avec les royaumes souterrains",
                                            "Négocier discrètement sa libération contre des informations, sans l'enrôler dans votre quête"]},
 'scene_16e_evasion_prison': {'options': ['Tuer le Bourreau et sortir vivant, même si ses secrets meurent avec lui',
                                          "L'interroger pendant le combat et arracher une réponse entre deux coups de hache",
                                          'Tenter de le capturer pour ramener à Aldor une preuve vivante des Cendres, quitte à compliquer votre propre fuite']},
 'scene_19_tour_du_soleil': {'options': ['Monter sans ralentir, avant que Morvayn ne dicte encore le rythme de cette ascension',
                                         'Attendre que Lyra vous rejoigne, quitte à laisser Morvayn gagner du temps',
                                         "Utiliser l'Œil d'Aeternis pour anticiper les pièges, même si chaque vision vous coûte un peu de vous et de votre mana",
                                         "Prendre un instant pour méditer aux côtés de Lyra avant de reprendre l'ascension"]},
 'scene_20_confrontation_morvayn': {'options': ['Combat agressif : forcer Morvayn à reculer, quitte à ouvrir votre garde',
                                                'Combat prudent : tenir, observer, transformer chaque seconde gagnée en réponse mesurée',
                                                "Utiliser l'Œil d'Aeternis pour lire le futur proche avant que Morvayn ne l'écrive à votre place, au prix d'une part de votre mana"],
                                    'options_2': ['Détruire les clones un à un, même si cela laisse Morvayn respirer et se réorganiser',
                                                  'Ignorer les clones et viser Morvayn directement'],
                                    'options_3': ["Achever Morvayn avant qu'il n'emporte encore une vérité dans les cendres",
                                                  "L'écouter révéler davantage sur Malakar, même si chaque mot peut vous détourner de la vengeance que vous croyiez vouloir",
                                                  'Tenter de le sauver malgré tout : vaincre un Porteur ne signifie peut-être pas le tuer']}}
