# Textes de choix de l'Acte 1.

ACT_1_CHOICES = {'scene_1a_vie_quotidienne': {'options': ["Rejoindre Garrick à la forge et scruter ce silence inhabituel dans ses mains",
                                          "Provoquer Marek devant les étals bondés : par jeu, par honneur, ou pour vous-même ?",
                                          "Accompagner Mira dans les ruelles pauvres et aider, sans un mot de plus, ceux que la fête du village oublie chaque année"]},
 'scene_1b_atelier_garrick': {'options': ["Lui demander pourquoi ses mains tremblent enfin devant vous",
                                          'Lui demander qui pourrait venir vous chercher, et pourquoi votre nom seul intéresse déjà des inconnus',
                                          "Lui promettre, malgré la peur qui serre votre poitrine, que vous ne fuirez pas Brumebois si le danger annoncé vient vraiment"],
                              'sujets': ["Parler du jour où Garrick vous a trouvé",
                                         "Parler de la première arme qu'il vous a confiée, et de la peur cachée derrière chaque leçon",
                                         "Ces cauchemars qu'il prétend ne pas entendre — pourquoi les tait-il ?",
                                         "Parler de ce qu'il regrette vraiment, maintenant que ses silences habituels, un à un, commencent enfin à se fissurer"]},
 'scene_1c_maison_de_mira': {'options': ["L'aider à préparer les remèdes du festival",
                                         'Lui confier vos rêves de tour noire et lui demander enfin ce qu’elle sait de votre arrivée à Brumebois, quitte à ce que la réponse blesse plus que le silence']},
 'scene_1d_jeux_du_festival': {'options': ["Affronter Marek dans le cercle d'entraînement, sous les rires du village",
                                           'Tenter le tir aux lanternes, là où l’adresse compte plus que vos secrets',
                                           'Quitter les jeux un moment pour aider les enfants du village à retrouver leur amulette perdue dans la paille',
                                           'Laisser les épreuves de côté et rejoindre les musiciens itinérants, pour danser un instant sans rien devoir prouver à personne']},
 'scene_1e_veillee_des_anciens': {'options': ['Que signifie cette flamme bleue ? Le demander tout haut, quitte à briser le silence des anciens',
                                              "Faire comme si rien ne s'était passé",
                                              "Suivre discrètement l'ancien qui quitte la place précipitamment, avant que les murmures de la foule ne reprennent",
                                              'Rester immobile et silencieux, à observer chaque visage des anciens, pour retenir ce que leurs mots ne diront jamais']},
 'scene_1f_travaux_et_marche': {'options': ["Passer chez le marchand et dépenser vos pièces en préparatifs",
                                            'Garder votre or pour la route à venir, parce que chaque détour risque d’avoir un prix que vous ne pouvez pas encore évaluer',
                                            'Repartir sans détour, pressé par un mauvais pressentiment'],
                                'travaux': ["Aider Garrick à ferrer les chevaux, dans la chaleur familière de la forge",
                                            "Escorter les marchands jusqu'au pont du moulin, là où la route cesse d’être tout à fait sûre depuis la nuit dernière",
                                            'Retenter votre chance aux jeux du festival',
                                            'Aider Mira à vendre ses remèdes et porter les paniers que personne d’autre ne remarque',
                                            'Ne pas travailler et garder vos forces — tant pis si Garrick juge votre prudence du coin de l’œil ?']},
 'chapitre_1': {'options': ['Accepter la mission devant tout le village, malgré la peur',
                            'Demander une récompense avant de risquer votre vie pour des inconnus, puis fouiller discrètement le corps du messager pour garder le médaillon sans témoin',
                            'Interroger les anciens sur le Septième Sceau — avant que la peur ne referme, une fois de plus, leurs bouches']},
 'scene_2a_les_premiers_cris': {'options': ['Courir vers la chapelle, là où le corps du messager et le médaillon royal attirent déjà le feu et la convoitise',
                                            'Courir vers la maison de Mira — votre premier réflexe',
                                            'Grimper sur le toit de la forge pour juger l’ampleur de l’attaque avant d’y plonger',
                                            'Rester figé un instant, sidéré, avant de choisir où porter secours']},
 'scene_2b_chercher_mira': {'options': ['Aider Mira à évacuer les blessés avant que la rue basse ne devienne un piège',
                                        "Que sait-elle vraiment de votre marque ? Le demander, même au milieu des flammes, puis lui confier une arme et courir vers la place"]},
 'scene_2c_place_en_flammes': {'options': ['Créer une diversion pour laisser fuir les derniers survivants',
                                           'Avancer à découvert pour forcer les Porteurs de Cendres à vous regarder, puis profiter du chaos pour contourner la place et chercher leur chef',
                                           'Rester dans l’ombre des flammes à épier leurs mouvements, avant de frapper au moment où ils s’y attendent le moins']},
 'scene_2e_morvayn_sur_la_place': {'options': ['Pourquoi vous cherche-t-il ? Il prononce votre nom comme une certitude ancienne',
                                               "Lui demander ce qu'il sait vraiment de Garrick, quitte à entendre une vérité empoisonnée qui changera tout",
                                               "L'attaquer avant qu'il ne disparaisse"]},
 'scene_3_la_fuite': {'options': ['Demander à Garrick qui vous a confié à lui et exiger enfin, ici, le début d’une histoire trop longtemps tue',
                                  'Prendre la carte et chercher une route de fuite',
                                  'Jurer de revenir sauver Garrick, même s’il vous ordonne déjà de partir sans lui']},
 'scene_4_grande_route': {'options': ['Partager vos rations avec les réfugiés épuisés, malgré la faim et la route encore longue',
                                      'Interroger les soldats blessés sur les Porteurs de Cendres',
                                      "Avancer tête basse sans attirer l'attention, pour survivre d’abord et comprendre ensuite, si le temps vous le permet"]},
 'scene_4a_campement_apres_brumebois': {'options': ['Relire les mots de Garrick, à la recherche d’une direction à suivre',
                                                    'Observer le Fragment du Temps, malgré la douleur familière',
                                                    "Monter la garde jusqu'à l'aube et refuser au sommeil le droit de vous trahir cette nuit encore",
                                                    'Dormir quelques heures, même mal — votre corps épuisé tiendra-t-il sans cela ?']},
 'scene_6_lyra': {'options': ['Lui accorder votre confiance, un temps',
                              'Exiger toute la vérité maintenant, avant que son silence trop poli ne devienne une autre chaîne à porter',
                              'Accepter son aide, mais garder vos distances et une main près de votre arme']},
 'scene_6a_campement_avec_lyra': {'options': ['Lui parler franchement de Garrick et de tout ce que vous venez de perdre en une seule nuit',
                                              "Que sait vraiment Ellorien de Morvayn, et des noms interdits aux jeunes éclaireurs ?",
                                              'Garder vos distances et vérifier le périmètre',
                                              'Observer ensemble les étoiles au-dessus de Val-Therys et laisser le silence, pour une fois, répondre à votre place']},
 'scene_7_val_therys': {'options': ["Explorer les archives effondrées",
                                    'Suivre les silhouettes temporelles, même si revivre leurs dernières secondes risque de vous traverser à votre tour',
                                    'Chercher un passage vers la tour mécanique avant l’arrivée des éclaireurs ennemis']},
 'scene_7a_quartier_des_nobles': {'options': ['Écouter le fantôme du sénéchal parler, une dernière fois, pour une cour morte depuis des siècles',
                                              'Briser le miroir qui maintient la scène figée, même si le Fragment en réclame un prix que vous ignorez encore',
                                              'Traverser sans troubler les morts']},
 'scene_7b_bibliotheque_engloutie': {'options': ["Chercher l'histoire de Malakar jeune",
                                                 'Chercher les premières mentions du Septième Sceau dans des livres dont les phrases changent sous vos yeux',
                                                 "Sauver des cartes précieuses avant que l'eau ne monte et n’emporte des routes déjà oubliées"]},
 'scene_7d_temple_du_cycle': {'options': ["Prier devant les sept cercles de l’autel — les Dragons-Dieux écoutent-ils encore quiconque ?",
                                          'Examiner la huitième forme volontairement effacée et comprendre pourquoi quelqu’un a voulu l’oublier à ce point',
                                          'Éteindre les cierges impossibles du temple']},
 'scene_7e_forum_des_heures': {'options': ['Acheter un objet au marchand fantôme',
                                           "Traverser l'arche de l'aube de massacre et accepter de voir, une fois encore, Val-Therys mourir sous vos yeux",
                                           "Demander au fantôme s'il a vu Morvayn passer entre deux heures brisées"]},
 'scene_10_sanctuaire_oublie': {'options': ["Étudier le relief de l'enfant marqué — un visage trop ancien pour être le vôtre",
                                            "Examiner l'image de Malakar jeune, avant la légende noire",
                                            'Chercher le symbole effacé derrière les Cristaux, là où la pierre elle-même semble encore avoir peur']}}
